apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sichek-deb-installer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: sichek-deb-installer
  template:
    metadata:
      labels:
        app: sichek-deb-installer
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: scitix.ai/gpu-type
                operator: Exists
      containers:
      - name: sichek-deb-installer
        image: registry-zhuoguang.siflow.cn/hisys/sicl-installer:25.11-1.cuda128-1
        securityContext:
          privileged: true
        command: ["/bin/bash", "-c"]
        args:
        - |
          set -eux
          cp /opt/sicl-25.11-1.cuda128.ubuntu2004.run /host/tmp/sicl-25.11-1.cuda128.ubuntu2004.run
          chmod +x /host/tmp/sicl-25.11-1.cuda128.ubuntu2004.run
          chroot /host /bin/bash /tmp/sicl-25.11-1.cuda128.ubuntu2004.run
          tail -f /dev/null
        volumeMounts:
        - name: host-root
          mountPath: /host
      volumes:
      - name: host-root
        hostPath:
          path: /
      restartPolicy: Always